# Generated by Django 3.1.7 on 2021-04-02 22:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('elevator_pitch', models.TextField(blank=True)),
                ('what_we_build_section', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full')), ('subheading', wagtail.core.blocks.CharBlock(form_classname='full')), ('html', wagtail.core.blocks.RawHTMLBlock(icon='code', label='Raw HTML'))], blank=True, null=True)),
                ('how_we_work_section', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full')), ('subheading', wagtail.core.blocks.CharBlock(form_classname='full')), ('html', wagtail.core.blocks.RawHTMLBlock(icon='code', label='Raw HTML'))], blank=True, null=True)),
                ('about_us_section', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full')), ('subheading', wagtail.core.blocks.CharBlock(form_classname='full')), ('founder', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=255)), ('bio', wagtail.core.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock('image'))], classname='full')), ('developer', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=255)), ('bio', wagtail.core.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], classname='full'))], blank=True, null=True)),
                ('clients_section', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full')), ('subheading', wagtail.core.blocks.CharBlock(form_classname='full')), ('logos', wagtail.core.blocks.StructBlock([('logo_1', wagtail.images.blocks.ImageChooserBlock()), ('logo_2', wagtail.images.blocks.ImageChooserBlock()), ('logo_3', wagtail.images.blocks.ImageChooserBlock()), ('logo_4', wagtail.images.blocks.ImageChooserBlock())], classname='full')), ('html', wagtail.core.blocks.RawHTMLBlock(icon='code', label='Raw HTML')), ('image', wagtail.images.blocks.ImageChooserBlock('image'))], blank=True, null=True)),
                ('the_quarry_section', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full')), ('subheading', wagtail.core.blocks.CharBlock(form_classname='full')), ('html', wagtail.core.blocks.RawHTMLBlock(icon='code', label='Raw HTML')), ('project', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=255)), ('description', wagtail.core.blocks.TextBlock()), ('widget', wagtail.core.blocks.TextBlock()), ('code', wagtail.core.blocks.TextBlock())]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TwoRockPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('tworockpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.tworockpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.tworockpage',),
        ),
    ]
