# Generated by Django 3.0.14 on 2021-06-06 01:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_us_section',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full')), ('subheading', wagtail.core.blocks.CharBlock(form_classname='full')), ('description', wagtail.core.blocks.RawHTMLBlock(icon='code', label='Raw HTML')), ('founder', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=255)), ('bio', wagtail.core.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock('image'))], classname='full')), ('developer', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=255)), ('bio', wagtail.core.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], classname='full'))], blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_images', to='wagtailimages.Image', verbose_name='Team Member Image')),
            ],
        ),
    ]
