# Generated by Django 3.0.14 on 2021-06-06 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20210605_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.TeamMember'),
        ),
    ]
