# Generated by Django 3.0.13 on 2021-06-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_homepage_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='team',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
