# Generated by Django 3.0.13 on 2021-07-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_dev_founder_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('organization', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=25)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
