# Generated by Django 3.1.7 on 2022-02-25 20:21

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_careerspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tworockpage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
